name: Arabam Scraper

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      COOKIE_B64: ${{ secrets.COOKIE_B64 }}

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Chrome ve ChromeDriver kur
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          wget https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip || wget https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bağımlılıkları yükle
        run: pip install selenium requests

      - name: Scraper'ı çalıştır
        run: python arabam_scraper.py

      - name: Değişiklikleri commit et
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "Arabam"
          git config --global user.email "arabam@anticomm.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/anticomm/ilan.git
          git add send_products.txt
          git diff --cached --quiet || git commit -m "Arabam scraper güncellemesi"
          git push
